-- Adds per-destination `include_raw` toggle, and expands every dataset's
-- seeded default CEF mapping to cover SOC monitoring priorities: bot
-- detection, WAF tuning, DDoS/network attribution, credential-leak
-- detection, insider threat, and 0-day/threat-intel hunting.
--
-- The `raw=<full record JSON>` extension (see includeRaw in
-- src/services/cef.ts) guarantees every field Cloudflare emits for a
-- dataset — including fields not named in these mappings, and fields
-- Cloudflare adds in the future — still reaches the SOC. These mappings
-- put the highest-value fields into named, SIEM-searchable CEF keys.
--
-- Keep the seeded `rules` JSON in sync with
-- src/shared/cef-defaults.ts (DEFAULT_MAPPING_RULES). See SOC_USE_CASES.md
-- for the detection scenarios these fields enable.

ALTER TABLE destinations ADD COLUMN include_raw INTEGER NOT NULL DEFAULT 1; -- 0|1

UPDATE mappings SET rules = '[{"cefKey":"src","sourceField":"ClientIP"},{"cefKey":"spt","sourceField":"ClientSrcPort"},{"cefKey":"dst","sourceField":"OriginIP"},{"cefKey":"dhost","sourceField":"ClientRequestHost"},{"cefKey":"request","sourceField":"ClientRequestURI"},{"cefKey":"requestMethod","sourceField":"ClientRequestMethod"},{"cefKey":"requestClientApplication","sourceField":"ClientRequestUserAgent"},{"cefKey":"externalId","sourceField":"RayID"},{"cefKey":"act","sourceField":"SecurityAction"},{"cefKey":"deviceExternalId","sourceField":"SecurityRuleID"},{"cefKey":"reason","sourceField":"SecurityRuleDescription"},{"cefKey":"cn1","label":"status","sourceField":"EdgeResponseStatus"},{"cefKey":"cn2","label":"botScore","sourceField":"BotScore"},{"cefKey":"cn3","label":"wafAttackScore","sourceField":"WAFAttackScore"},{"cefKey":"cs1","label":"protocol","sourceField":"ClientRequestProtocol"},{"cefKey":"cs2","label":"sslProto","sourceField":"ClientSSLProtocol"},{"cefKey":"cs3","label":"cacheStatus","sourceField":"CacheCacheStatus"},{"cefKey":"cs4","label":"country","sourceField":"ClientCountry"},{"cefKey":"cs5","label":"coloCode","sourceField":"EdgeColoCode"},{"cefKey":"cs6","label":"zone","sourceField":"ZoneName"},{"cefKey":"cs7","label":"securityActions","sourceField":"SecurityActions"},{"cefKey":"cs8","label":"securityRuleIds","sourceField":"SecurityRuleIDs"},{"cefKey":"cs9","label":"securitySources","sourceField":"SecuritySources"},{"cefKey":"cs10","label":"clientAsn","sourceField":"ClientASN"},{"cefKey":"cs11","label":"clientIpClass","sourceField":"ClientIPClass"},{"cefKey":"cs12","label":"botScoreSrc","sourceField":"BotScoreSrc"},{"cefKey":"cs13","label":"botTags","sourceField":"BotTags"},{"cefKey":"cs14","label":"ja3Hash","sourceField":"JA3Hash"},{"cefKey":"cs15","label":"leakedCredResult","sourceField":"LeakedCredentialCheckResult"},{"cefKey":"flexString1","label":"edgePathingSrc","sourceField":"EdgePathingSrc"},{"cefKey":"flexString2","label":"ja4","sourceField":"JA4"}]', updated_at = datetime('now') WHERE id = 'default-http-requests';

UPDATE mappings SET rules = '[{"cefKey":"src","sourceField":"ClientIP"},{"cefKey":"dhost","sourceField":"ClientRequestHost"},{"cefKey":"request","sourceField":"ClientRequestPath"},{"cefKey":"requestMethod","sourceField":"ClientRequestMethod"},{"cefKey":"requestClientApplication","sourceField":"ClientRequestUserAgent"},{"cefKey":"externalId","sourceField":"RayID"},{"cefKey":"act","sourceField":"Action"},{"cefKey":"deviceExternalId","sourceField":"RuleID"},{"cefKey":"reason","sourceField":"Description"},{"cefKey":"cn1","label":"status","sourceField":"EdgeResponseStatus"},{"cefKey":"cn2","label":"originStatus","sourceField":"OriginResponseStatus"},{"cefKey":"cn3","label":"aiInjectionScore","sourceField":"AISecurityInjectionScore"},{"cefKey":"cs1","label":"querystring","sourceField":"ClientRequestQuery"},{"cefKey":"cs2","label":"securitySource","sourceField":"Source"},{"cefKey":"cs3","label":"country","sourceField":"ClientCountry"},{"cefKey":"cs4","label":"coloCode","sourceField":"EdgeColoCode"},{"cefKey":"cs5","label":"zone","sourceField":"ZoneName"},{"cefKey":"cs6","label":"ruleRef","sourceField":"Ref"},{"cefKey":"cs7","label":"clientAsn","sourceField":"ClientASN"},{"cefKey":"cs8","label":"clientAsnDescription","sourceField":"ClientASNDescription"},{"cefKey":"cs9","label":"clientIpClass","sourceField":"ClientIPClass"},{"cefKey":"cs10","label":"leakedCredResult","sourceField":"LeakedCredentialCheckResult"},{"cefKey":"cs11","label":"originatorRayId","sourceField":"OriginatorRayID"},{"cefKey":"flexString1","label":"matchIndex","sourceField":"MatchIndex"},{"cefKey":"flexString2","label":"fraudUserId","sourceField":"FraudUserID"}]', updated_at = datetime('now') WHERE id = 'default-firewall-events';

UPDATE mappings SET rules = '[{"cefKey":"src","sourceField":"SourceIP"},{"cefKey":"request","sourceField":"QueryName"},{"cefKey":"cn1","label":"responseCode","sourceField":"ResponseCode"},{"cefKey":"cn2","label":"queryTypeId","sourceField":"QueryType"},{"cefKey":"cs1","label":"coloCode","sourceField":"ColoCode"},{"cefKey":"cs2","label":"cached","sourceField":"ResponseCached"},{"cefKey":"cs3","label":"ednsSubnet","sourceField":"EDNSSubnet"}]', updated_at = datetime('now') WHERE id = 'default-dns-logs';

UPDATE mappings SET rules = '[{"cefKey":"src","sourceField":"ClientIP"},{"cefKey":"spt","sourceField":"ClientPort"},{"cefKey":"dst","sourceField":"OriginIP"},{"cefKey":"dpt","sourceField":"OriginPort"},{"cefKey":"act","sourceField":"Event"},{"cefKey":"proto","sourceField":"ClientProto"},{"cefKey":"cn1","label":"status","sourceField":"Status"},{"cefKey":"cn2","label":"clientBytes","sourceField":"ClientBytes"},{"cefKey":"cn3","label":"originBytes","sourceField":"OriginBytes"},{"cefKey":"cs1","label":"application","sourceField":"Application"},{"cefKey":"cs2","label":"country","sourceField":"ClientCountry"},{"cefKey":"cs3","label":"tlsStatus","sourceField":"ClientTlsStatus"},{"cefKey":"cs4","label":"ipFirewallMatch","sourceField":"ClientMatchedIpFirewall"},{"cefKey":"cs5","label":"clientAsn","sourceField":"ClientAsn"},{"cefKey":"cs6","label":"sni","sourceField":"ClientTlsClientHelloServerName"},{"cefKey":"cs7","label":"originTlsFingerprint","sourceField":"OriginTlsFingerprint"},{"cefKey":"cs8","label":"originTlsStatus","sourceField":"OriginTlsStatus"},{"cefKey":"cs9","label":"ipFirewallEnabled","sourceField":"IpFirewall"}]', updated_at = datetime('now') WHERE id = 'default-spectrum-events';

UPDATE mappings SET rules = '[{"cefKey":"src","sourceField":"SourceIP"},{"cefKey":"spt","sourceField":"SourcePort"},{"cefKey":"dst","sourceField":"DestinationIP"},{"cefKey":"dpt","sourceField":"DestinationPort"},{"cefKey":"dhost","sourceField":"HTTPHost"},{"cefKey":"request","sourceField":"URL"},{"cefKey":"requestMethod","sourceField":"HTTPMethod"},{"cefKey":"requestClientApplication","sourceField":"UserAgent"},{"cefKey":"act","sourceField":"Action"},{"cefKey":"suser","sourceField":"Email"},{"cefKey":"externalId","sourceField":"RequestID"},{"cefKey":"deviceExternalId","sourceField":"PolicyID"},{"cefKey":"reason","sourceField":"BlockedFileReason"},{"cefKey":"fileHash","sourceField":"BlockedFileHash"},{"cefKey":"fileName","sourceField":"BlockedFileName"},{"cefKey":"fileType","sourceField":"BlockedFileType"},{"cefKey":"fileSize","sourceField":"BlockedFileSize"},{"cefKey":"cn1","label":"status","sourceField":"HTTPStatusCode"},{"cefKey":"cs1","label":"policyName","sourceField":"PolicyName"},{"cefKey":"cs2","label":"deviceName","sourceField":"DeviceName"},{"cefKey":"cs3","label":"deviceId","sourceField":"DeviceID"},{"cefKey":"cs4","label":"userId","sourceField":"UserID"},{"cefKey":"cs5","label":"srcCountry","sourceField":"SourceIPCountryCode"},{"cefKey":"cs6","label":"quarantined","sourceField":"Quarantined"},{"cefKey":"cs7","label":"isIsolated","sourceField":"IsIsolated"},{"cefKey":"cs8","label":"dlpDownloadProfiles","sourceField":"DownloadMatchedDlpProfiles"},{"cefKey":"cs9","label":"dlpUploadProfiles","sourceField":"UploadMatchedDlpProfiles"},{"cefKey":"cs10","label":"applicationNames","sourceField":"ApplicationNames"},{"cefKey":"cs11","label":"categoryNames","sourceField":"CategoryNames"},{"cefKey":"cs12","label":"sessionId","sourceField":"SessionID"},{"cefKey":"cs13","label":"virtualNetworkName","sourceField":"VirtualNetworkName"},{"cefKey":"cs14","label":"untrustedCertAction","sourceField":"UntrustedCertificateAction"},{"cefKey":"cs15","label":"forensicCopyStatus","sourceField":"ForensicCopyStatus"},{"cefKey":"flexString1","label":"sourceInternalIp","sourceField":"SourceInternalIP"},{"cefKey":"flexString2","label":"registrationId","sourceField":"RegistrationID"}]', updated_at = datetime('now') WHERE id = 'default-gateway-http';

UPDATE mappings SET rules = '[{"cefKey":"src","sourceField":"SrcIP"},{"cefKey":"spt","sourceField":"SrcPort"},{"cefKey":"dst","sourceField":"DstIP"},{"cefKey":"dpt","sourceField":"DstPort"},{"cefKey":"suser","sourceField":"Email"},{"cefKey":"act","sourceField":"ResolverDecision"},{"cefKey":"request","sourceField":"QueryName"},{"cefKey":"externalId","sourceField":"QueryID"},{"cefKey":"deviceExternalId","sourceField":"PolicyID"},{"cefKey":"cn1","label":"rcode","sourceField":"RCode"},{"cefKey":"cn2","label":"querySize","sourceField":"QuerySize"},{"cefKey":"cn3","label":"responseTimeMs","sourceField":"ResponseTimeMs"},{"cefKey":"cs1","label":"queryType","sourceField":"QueryTypeName"},{"cefKey":"cs2","label":"policyName","sourceField":"PolicyName"},{"cefKey":"cs3","label":"deviceName","sourceField":"DeviceName"},{"cefKey":"cs4","label":"location","sourceField":"Location"},{"cefKey":"cs5","label":"srcCountry","sourceField":"SrcIPCountryCode"},{"cefKey":"cs6","label":"matchedCategoryNames","sourceField":"MatchedCategoryNames"},{"cefKey":"cs7","label":"matchedIndicatorFeedNames","sourceField":"MatchedIndicatorFeedNames"},{"cefKey":"cs8","label":"resolvedIps","sourceField":"ResolvedIPs"},{"cefKey":"cs9","label":"resolvedIpCountryCodes","sourceField":"ResolvedIPCountryCodes"},{"cefKey":"cs10","label":"userId","sourceField":"UserID"},{"cefKey":"cs11","label":"deviceId","sourceField":"DeviceID"},{"cefKey":"cs12","label":"cnames","sourceField":"CNAMEs"},{"cefKey":"cs13","label":"applicationName","sourceField":"ApplicationName"},{"cefKey":"cs14","label":"isResponseCached","sourceField":"IsResponseCached"},{"cefKey":"cs15","label":"protocol","sourceField":"Protocol"},{"cefKey":"flexString1","label":"tenantId","sourceField":"TenantID"},{"cefKey":"flexString2","label":"edeErrors","sourceField":"EDEErrors"}]', updated_at = datetime('now') WHERE id = 'default-gateway-dns';

UPDATE mappings SET rules = '[{"cefKey":"src","sourceField":"SourceIP"},{"cefKey":"spt","sourceField":"SourcePort"},{"cefKey":"dst","sourceField":"DestinationIP"},{"cefKey":"dpt","sourceField":"DestinationPort"},{"cefKey":"suser","sourceField":"Email"},{"cefKey":"act","sourceField":"Action"},{"cefKey":"proto","sourceField":"TransportProtocol"},{"cefKey":"externalId","sourceField":"SessionID"},{"cefKey":"deviceExternalId","sourceField":"PolicyID"},{"cefKey":"cs1","label":"sni","sourceField":"SNI"},{"cefKey":"cs2","label":"detectedProtocol","sourceField":"DetectedProtocol"},{"cefKey":"cs3","label":"policyName","sourceField":"PolicyName"},{"cefKey":"cs4","label":"deviceName","sourceField":"DeviceName"},{"cefKey":"cs5","label":"srcCountry","sourceField":"SourceIPCountryCode"},{"cefKey":"cs6","label":"dstCountry","sourceField":"DestinationIPCountryCode"},{"cefKey":"cs7","label":"userId","sourceField":"UserID"},{"cefKey":"cs8","label":"deviceId","sourceField":"DeviceID"},{"cefKey":"cs9","label":"applicationNames","sourceField":"ApplicationNames"},{"cefKey":"cs10","label":"categoryNames","sourceField":"CategoryNames"},{"cefKey":"cs11","label":"virtualNetworkName","sourceField":"VirtualNetworkName"},{"cefKey":"cs12","label":"overrideIp","sourceField":"OverrideIP"},{"cefKey":"cs13","label":"tenantId","sourceField":"TenantID"},{"cefKey":"cs14","label":"sourceInternalIp","sourceField":"SourceInternalIP"},{"cefKey":"cs15","label":"registrationId","sourceField":"RegistrationID"}]', updated_at = datetime('now') WHERE id = 'default-gateway-network';

UPDATE mappings SET rules = '[{"cefKey":"suser","sourceField":"ActorEmail"},{"cefKey":"src","sourceField":"ActorIP"},{"cefKey":"act","sourceField":"ActionType"},{"cefKey":"outcome","sourceField":"ActionResult"},{"cefKey":"externalId","sourceField":"ID"},{"cefKey":"deviceExternalId","sourceField":"ResourceID"},{"cefKey":"duser","sourceField":"OwnerID"},{"cefKey":"cs1","label":"resourceType","sourceField":"ResourceType"},{"cefKey":"cs2","label":"actorType","sourceField":"ActorType"},{"cefKey":"cs3","label":"interface","sourceField":"Interface"},{"cefKey":"cs4","label":"actorId","sourceField":"ActorID"},{"cefKey":"cs5","label":"metadata","sourceField":"Metadata"},{"cefKey":"cs6","label":"oldValue","sourceField":"OldValue"},{"cefKey":"cs7","label":"newValue","sourceField":"NewValue"}]', updated_at = datetime('now') WHERE id = 'default-audit-logs';

UPDATE mappings SET rules = '[{"cefKey":"act","sourceField":"Type"},{"cefKey":"cs1","label":"phase","sourceField":"Phase"},{"cefKey":"cs2","label":"asnDescription","sourceField":"ClientIPASNDescription"},{"cefKey":"cs3","label":"country","sourceField":"ClientIPCountry"},{"cefKey":"cs4","label":"coloCode","sourceField":"LastKnownGoodColoCode"},{"cefKey":"cn1","label":"asn","sourceField":"ClientIPASN"}]', updated_at = datetime('now') WHERE id = 'default-nel-reports';

