import { connect } from "cloudflare:sockets";
import type { Destination } from "@logpush-syslog-hub/shared";

/**
 * Minimal shape of a Workers VPC Network binding's connect() method.
 * Not generated by `wrangler types` because the binding is optional
 * (commented out in wrangler.jsonc until a Cloudflare Tunnel is configured).
 */
export interface VpcNetworkBinding {
  connect(address: string): Promise<Socket>;
}

export class SyslogDeliveryError extends Error {}

/**
 * Frame a syslog message per the destination's chosen framing:
 *  - "rfc6587": octet-count prefix `"<byteLength> "` before the message.
 *  - "newline": the message followed by a trailing `\n`.
 * Returns the raw byte chunks to write to the socket, in order.
 */
export function frameMessage(message: string, frame: "rfc6587" | "newline"): Uint8Array[] {
  const encoder = new TextEncoder();
  const msgBytes = encoder.encode(message);
  if (frame === "rfc6587") {
    return [encoder.encode(`${msgBytes.byteLength} `), msgBytes];
  }
  return [msgBytes, encoder.encode("\n")];
}

/**
 * Send one already-formatted syslog message over TCP to a destination.
 * Supports:
 *  - transport "direct": plain TCP via `cloudflare:sockets` connect() (no TLS in this build).
 *  - transport "vpc": plaintext TCP via a Workers VPC Network binding
 *    (reaches any host:port behind the bound Cloudflare Tunnel/Mesh).
 * Framing:
 *  - "rfc6587": octet-count prefix `"<byteLength> "` before the message (recommended;
 *    matches RFC 6587 and NetWitness's `syslog-lengthprefix-tcp` event source).
 *  - "newline": a trailing `\n` after the message (classic line-delimited syslog-tcp).
 */
export async function sendSyslogMessage(
  destination: Pick<Destination, "host" | "port" | "transport" | "frame">,
  message: string,
  vpcBinding: VpcNetworkBinding | undefined,
): Promise<void> {
  let socket: Socket;
  if (destination.transport === "vpc") {
    if (!vpcBinding) {
      throw new SyslogDeliveryError(
        "Destination transport is 'vpc' but no SYSLOG_VPC binding is configured. " +
          "Add a vpc_networks binding to wrangler.jsonc and redeploy.",
      );
    }
    socket = await vpcBinding.connect(`${destination.host}:${destination.port}`);
  } else {
    socket = connect(
      { hostname: destination.host, port: destination.port },
      { secureTransport: "off", allowHalfOpen: false },
    );
  }

  const writer = socket.writable.getWriter();
  try {
    for (const chunk of frameMessage(message, destination.frame)) {
      await writer.write(chunk);
    }
  } finally {
    await writer.close().catch(() => undefined);
  }
  await socket.closed.catch(() => undefined);
}
